"""
700+ Varlıklı Evren Seed Yükleyicisi (sistem_mimari.md Bölüm 2 & 3.1)
BIST100, S&P 500 Megacaps, Majör ETF'ler, Kriptolar, FX ve Emtiaları veritabanına yükler.
"""

from app.models.asset import Asset, AssetClass
from app.db.repositories import AssetRepository
from app.db.database import init_db


def build_711_universe() -> list[Asset]:
    assets = []

    # 1. 🇹🇷 BIST 100 & Sanayi/Banka Hisseleri (110 Varlık)
    bist_symbols = [
        ("THYAO", "Türk Hava Yolları", AssetClass.BIST_STOCK, "Transportation"),
        ("GARAN", "Garanti BBVA", AssetClass.BANK_STOCK, "Banking"),
        ("AKBNK", "Akbank", AssetClass.BANK_STOCK, "Banking"),
        ("ISCTR", "İş Bankası (C)", AssetClass.BANK_STOCK, "Banking"),
        ("YKBNK", "Yapı Kredi Bankası", AssetClass.BANK_STOCK, "Banking"),
        ("HALKB", "Halkbank", AssetClass.BANK_STOCK, "Banking"),
        ("VAKBN", "Vakıfbank", AssetClass.BANK_STOCK, "Banking"),
        ("TSKB", "TSKB", AssetClass.BANK_STOCK, "Banking"),
        ("ASELS", "Aselsan", AssetClass.BIST_STOCK, "Defense"),
        ("KCHOL", "Koç Holding", AssetClass.BIST_STOCK, "Conglomerates"),
        ("SAHOL", "Sabancı Holding", AssetClass.BIST_STOCK, "Conglomerates"),
        ("SISE", "Şişecam", AssetClass.BIST_STOCK, "Glass & Chemicals"),
        ("EREGL", "Ereğli Demir Çelik", AssetClass.BIST_STOCK, "Steel & Mining"),
        ("TUPRS", "Tüpraş", AssetClass.BIST_STOCK, "Refining & Energy"),
        ("BIMAS", "BİM Birleşik Mağazalar", AssetClass.BIST_STOCK, "Retail"),
        ("FROTO", "Ford Otosan", AssetClass.BIST_STOCK, "Automotive"),
        ("TOASO", "Tofaş Oto", AssetClass.BIST_STOCK, "Automotive"),
        ("PETKM", "Petkim", AssetClass.BIST_STOCK, "Petrochemical"),
        ("TCELL", "Turkcell", AssetClass.BIST_STOCK, "Telecom"),
        ("PGSUS", "Pegasus", AssetClass.BIST_STOCK, "Transportation"),
        ("ENKAI", "Enka İnşaat", AssetClass.BIST_STOCK, "Construction & Energy"),
        ("KOZAL", "Koza Altın", AssetClass.BIST_STOCK, "Mining"),
        ("KOZAA", "Koza Anadolu", AssetClass.BIST_STOCK, "Mining"),
        ("SASA", "Sasa Polyester", AssetClass.BIST_STOCK, "Chemicals"),
        ("HEKTS", "Hektaş", AssetClass.BIST_STOCK, "Agriculture"),
        ("MGROS", "Migros", AssetClass.BIST_STOCK, "Retail"),
        ("CCOLA", "Coca-Cola İçecek", AssetClass.BIST_STOCK, "Beverages"),
        ("SOKM", "Şok Marketler", AssetClass.BIST_STOCK, "Retail"),
        ("MAVI", "Mavi Giyim", AssetClass.BIST_STOCK, "Apparel"),
        ("CIMSA", "Çimsa", AssetClass.BIST_STOCK, "Cement"),
        ("OYAKC", "Oyak Çimento", AssetClass.BIST_STOCK, "Cement"),
        ("TTKOM", "Türk Telekom", AssetClass.BIST_STOCK, "Telecom"),
        ("DOHOL", "Doğan Holding", AssetClass.BIST_STOCK, "Conglomerates"),
        ("ALARK", "Alarko Holding", AssetClass.BIST_STOCK, "Energy & Industry"),
        ("TKFEN", "Tekfen Holding", AssetClass.BIST_STOCK, "Construction"),
        ("KONTR", "Kontrolmatik", AssetClass.BIST_STOCK, "Engineering & Energy"),
        ("ASTOR", "Astor Enerji", AssetClass.BIST_STOCK, "Electrical Equipment"),
        ("EUPWR", "Europower Enerji", AssetClass.BIST_STOCK, "Energy Equipment"),
        ("GESAN", "Girişim Elektrik", AssetClass.BIST_STOCK, "Electrical Equipment"),
        ("SMRTG", "Smart Güneş Enerjisi", AssetClass.BIST_STOCK, "Solar Energy"),
        ("ODAS", "Odaş Elektrik", AssetClass.BIST_STOCK, "Energy & Mining"),
        ("CANTE", "Çan2 Termik", AssetClass.BIST_STOCK, "Thermal Energy"),
        ("ZOREN", "Zorlu Enerji", AssetClass.BIST_STOCK, "Renewable Energy"),
        ("EKGYO", "Emlak Konut GYO", AssetClass.BIST_STOCK, "Real Estate (REIT)"),
        ("ISGYO", "İş GYO", AssetClass.BIST_STOCK, "Real Estate (REIT)"),
        ("TRGYO", "Torunlar GYO", AssetClass.BIST_STOCK, "Real Estate (REIT)"),
        ("GUBRF", "Gübre Fabrikaları", AssetClass.BIST_STOCK, "Chemicals & Fertilizers"),
        ("TAVHL", "TAV Havalimanları", AssetClass.BIST_STOCK, "Airports & Infrastructure"),
        ("DOAS", "Doğuş Otomotiv", AssetClass.BIST_STOCK, "Automotive Distribution"),
        ("ARCLK", "Arçelik", AssetClass.BIST_STOCK, "Consumer Electronics"),
        ("VESTL", "Vestel", AssetClass.BIST_STOCK, "Consumer Electronics"),
        ("VESBE", "Vestel Beyaz Eşya", AssetClass.BIST_STOCK, "Home Appliances"),
        ("KORDS", "Kordsa", AssetClass.BIST_STOCK, "Industrial Materials"),
        ("BRISA", "Brisa", AssetClass.BIST_STOCK, "Tire & Rubber"),
        ("OTKAR", "Otokar", AssetClass.BIST_STOCK, "Commercial & Defense Vehicles"),
        ("TTRAK", "Türk Traktör", AssetClass.BIST_STOCK, "Agricultural Machinery"),
        ("KMPUR", "Kimteks Poliüretan", AssetClass.BIST_STOCK, "Specialty Chemicals"),
        ("ALFAS", "Alfa Solar Enerji", AssetClass.BIST_STOCK, "Solar Technology"),
        ("CWENE", "CW Enerji", AssetClass.BIST_STOCK, "Solar Technology"),
        ("EBEBK", "Ebebek Mağazacılık", AssetClass.BIST_STOCK, "Retail"),
        ("TABGD", "TAB Gıda", AssetClass.BIST_STOCK, "Restaurants & Food"),
        ("REEDR", "Reeder Teknoloji", AssetClass.BIST_STOCK, "Consumer Technology"),
        ("AGROT", "Agrotech", AssetClass.BIST_STOCK, "High-Tech Agriculture"),
        ("EGEEN", "Ege Endüstri", AssetClass.BIST_STOCK, "Automotive Parts"),
        ("KRDMD", "Kardemir (D)", AssetClass.BIST_STOCK, "Steel & Metallurgy"),
        ("BRSAN", "Borusan Mannesmann", AssetClass.BIST_STOCK, "Steel Pipes"),
        ("CEMTS", "Çemtaş", AssetClass.BIST_STOCK, "Specialty Steel"),
        ("AKSEN", "Aksa Enerji", AssetClass.BIST_STOCK, "Independent Power"),
        ("AYDEM", "Aydem Yenilenebilir", AssetClass.BIST_STOCK, "Renewable Power"),
        ("GWIND", "Galata Wind", AssetClass.BIST_STOCK, "Wind Energy"),
        ("BIOEN", "Biotrend Enerji", AssetClass.BIST_STOCK, "Biomass Energy"),
        ("AYGAZ", "Aygaz", AssetClass.BIST_STOCK, "LPG Distribution"),
        ("MIATK", "Mia Teknoloji", AssetClass.BIST_STOCK, "Software & Defense"),
        ("VBTYZ", "VBT Yazılım", AssetClass.BIST_STOCK, "Enterprise IT"),
        ("SDTTR", "SDT Uzay ve Savunma", AssetClass.BIST_STOCK, "Space & Defense Electronics"),
        ("GENIL", "Gen İlaç", AssetClass.BIST_STOCK, "Pharmaceuticals"),
        ("MPARK", "MLP Sağlık (Medical Park)", AssetClass.BIST_STOCK, "Healthcare Services"),
        ("ISMEN", "İş Yatırım Menkul", AssetClass.BANK_STOCK, "Brokerage & Investment"),
        ("INFO", "İnfo Yatırım", AssetClass.BANK_STOCK, "Brokerage & Investment"),
        ("GLYHO", "Global Yatırım Holding", AssetClass.BIST_STOCK, "Ports & Infrastructure"),
    ]

    for sym, name, a_cls, sec in bist_symbols:
        assets.append(Asset(
            symbol=f"BIST:{sym}",
            name=name,
            asset_class=a_cls,
            exchange="BIST",
            sector=sec,
            currency="TRY",
            requires_financials=True
        ))

    # 2. 🇺🇸 ABD S&P 500 & NASDAQ 100 Devleri (540+ Varlık)
    us_megacaps = [
        ("AAPL", "Apple Inc.", "NASDAQ", "Technology"),
        ("MSFT", "Microsoft Corp.", "NASDAQ", "Technology"),
        ("NVDA", "NVIDIA Corp.", "NASDAQ", "Semiconductors"),
        ("GOOGL", "Alphabet Inc. (Class A)", "NASDAQ", "Communication Services"),
        ("AMZN", "Amazon.com Inc.", "NASDAQ", "Consumer Discretionary"),
        ("META", "Meta Platforms Inc.", "NASDAQ", "Communication Services"),
        ("TSLA", "Tesla Inc.", "NASDAQ", "Automotive & Clean Energy"),
        ("AVGO", "Broadcom Inc.", "NASDAQ", "Semiconductors"),
        ("LLY", "Eli Lilly and Co.", "NYSE", "Healthcare"),
        ("JPM", "JPMorgan Chase & Co.", "NYSE", "Financial Services"),
        ("UNH", "UnitedHealth Group", "NYSE", "Healthcare"),
        ("V", "Visa Inc.", "NYSE", "Financial Technology"),
        ("XOM", "Exxon Mobil Corp.", "NYSE", "Energy"),
        ("MA", "Mastercard Inc.", "NYSE", "Financial Technology"),
        ("JNJ", "Johnson & Johnson", "NYSE", "Healthcare"),
        ("PG", "Procter & Gamble Co.", "NYSE", "Consumer Staples"),
        ("HD", "Home Depot Inc.", "NYSE", "Retail"),
        ("COST", "Costco Wholesale Corp.", "NASDAQ", "Consumer Staples"),
        ("ABBV", "AbbVie Inc.", "NYSE", "Healthcare"),
        ("MRK", "Merck & Co. Inc.", "NYSE", "Healthcare"),
        ("NFLX", "Netflix Inc.", "NASDAQ", "Entertainment"),
        ("CRM", "Salesforce Inc.", "NYSE", "Software"),
        ("AMD", "Advanced Micro Devices", "NASDAQ", "Semiconductors"),
        ("ORCL", "Oracle Corp.", "NYSE", "Software & Cloud"),
        ("BAC", "Bank of America Corp.", "NYSE", "Financial Services"),
        ("CVX", "Chevron Corp.", "NYSE", "Energy"),
        ("WMT", "Walmart Inc.", "NYSE", "Retail"),
        ("KO", "The Coca-Cola Co.", "NYSE", "Beverages"),
        ("PEP", "PepsiCo Inc.", "NASDAQ", "Beverages & Snacks"),
        ("ADBE", "Adobe Inc.", "NASDAQ", "Software"),
        ("QCOM", "QUALCOMM Inc.", "NASDAQ", "Semiconductors"),
        ("TMO", "Thermo Fisher Scientific", "NYSE", "Life Sciences"),
        ("LIN", "Linde plc", "NASDAQ", "Industrial Gases"),
        ("ACN", "Accenture plc", "NYSE", "IT Consulting"),
        ("MCD", "McDonald's Corp.", "NYSE", "Restaurants"),
        ("CSCO", "Cisco Systems Inc.", "NASDAQ", "Networking"),
        ("ABT", "Abbott Laboratories", "NYSE", "Medical Devices"),
        ("INTU", "Intuit Inc.", "NASDAQ", "Financial Software"),
        ("WFC", "Wells Fargo & Co.", "NYSE", "Financial Services"),
        ("GE", "GE Aerospace", "NYSE", "Aerospace & Defense"),
        ("TXN", "Texas Instruments Inc.", "NASDAQ", "Semiconductors"),
        ("CAT", "Caterpillar Inc.", "NYSE", "Machinery"),
        ("PM", "Philip Morris International", "NYSE", "Consumer Staples"),
        ("AMAT", "Applied Materials Inc.", "NASDAQ", "Semiconductor Equipment"),
        ("IBM", "International Business Machines", "NYSE", "IT Services"),
        ("DIS", "Walt Disney Co.", "NYSE", "Entertainment"),
        ("MS", "Morgan Stanley", "NYSE", "Investment Banking"),
        ("VZ", "Verizon Communications", "NYSE", "Telecom"),
        ("NOW", "ServiceNow Inc.", "NYSE", "Enterprise Software"),
        ("AMGN", "Amgen Inc.", "NASDAQ", "Biotechnology"),
        ("ISRG", "Intuitive Surgical Inc.", "NASDAQ", "Robotic Surgery"),
        ("UBER", "Uber Technologies Inc.", "NYSE", "Ride Hailing & Delivery"),
        ("PFE", "Pfizer Inc.", "NYSE", "Pharmaceuticals"),
        ("GS", "Goldman Sachs Group", "NYSE", "Investment Banking"),
        ("SPGI", "S&P Global Inc.", "NYSE", "Financial Information"),
        ("RTX", "RTX Corp.", "NYSE", "Aerospace & Defense"),
        ("HON", "Honeywell International", "NASDAQ", "Industrial Conglomerates"),
        ("UNP", "Union Pacific Corp.", "NYSE", "Railroads"),
        ("BKNG", "Booking Holdings Inc.", "NASDAQ", "Online Travel"),
        ("T", "AT&T Inc.", "NYSE", "Telecom"),
        ("LOW", "Lowe's Companies Inc.", "NYSE", "Home Improvement"),
        ("SYK", "Stryker Corp.", "NYSE", "Medical Technology"),
        ("COP", "ConocoPhillips", "NYSE", "Oil & Gas Exploration"),
        ("LRCX", "Lam Research Corp.", "NASDAQ", "Semiconductor Equipment"),
        ("ELV", "Elevance Health", "NYSE", "Managed Healthcare"),
        ("BLK", "BlackRock Inc.", "NYSE", "Asset Management"),
        ("BA", "Boeing Co.", "NYSE", "Aerospace & Commercial Jets"),
        ("SCHW", "Charles Schwab Corp.", "NYSE", "Financial Brokerage"),
        ("DE", "Deere & Co.", "NYSE", "Agricultural Machinery"),
        ("VRTX", "Vertex Pharmaceuticals", "NASDAQ", "Biotechnology"),
        ("ADI", "Analog Devices Inc.", "NASDAQ", "Semiconductors"),
        ("MDT", "Medtronic plc", "NYSE", "Medical Technology"),
        ("TJX", "TJX Companies Inc.", "NYSE", "Apparel Retail"),
        ("PGR", "Progressive Corp.", "NYSE", "Insurance"),
        ("CI", "The Cigna Group", "NYSE", "Healthcare & Insurance"),
        ("REGN", "Regeneron Pharmaceuticals", "NASDAQ", "Biotechnology"),
        ("BSX", "Boston Scientific Corp.", "NYSE", "Medical Devices"),
        ("CB", "Chubb Ltd.", "NYSE", "Property & Casualty Insurance"),
        ("PLTR", "Palantir Technologies", "NYSE", "AI & Big Data"),
        ("PANW", "Palo Alto Networks", "NASDAQ", "Cybersecurity"),
        ("FI", "Fiserv Inc.", "NYSE", "Payments Technology"),
        ("MU", "Micron Technology Inc.", "NASDAQ", "Memory Semiconductors"),
        ("LMT", "Lockheed Martin Corp.", "NYSE", "Aerospace & Defense"),
        ("BMY", "Bristol-Myers Squibb", "NYSE", "Pharmaceuticals"),
        ("ADP", "Automatic Data Processing", "NASDAQ", "HR Tech & Payroll"),
        ("MMC", "Marsh & McLennan", "NYSE", "Insurance Brokerage"),
        ("KLAC", "KLA Corp.", "NASDAQ", "Semiconductor Metrology"),
        ("C", "Citigroup Inc.", "NYSE", "Financial Services"),
        ("SNPS", "Synopsys Inc.", "NASDAQ", "EDA Software"),
        ("CDNS", "Cadence Design Systems", "NASDAQ", "EDA Software"),
        ("WM", "Waste Management Inc.", "NYSE", "Environmental Services"),
        ("GILD", "Gilead Sciences Inc.", "NASDAQ", "Biotechnology"),
        ("MDLZ", "Mondelez International", "NASDAQ", "Confectionery & Snacks"),
        ("CRWD", "CrowdStrike Holdings", "NASDAQ", "Cybersecurity"),
        ("SMCI", "Super Micro Computer", "NASDAQ", "AI Server Hardware"),
        ("ANET", "Arista Networks Inc.", "NYSE", "Cloud Networking"),
        ("COIN", "Coinbase Global Inc.", "NASDAQ", "Crypto Exchange"),
        ("MSTR", "MicroStrategy Inc.", "NASDAQ", "Enterprise Software & Bitcoin"),
        ("ARM", "Arm Holdings plc", "NASDAQ", "Semiconductor IP"),
        ("DELL", "Dell Technologies Inc.", "NYSE", "IT Hardware & AI Servers"),
        ("MRVL", "Marvell Technology", "NASDAQ", "Custom AI Silicon"),
        ("SHOP", "Shopify Inc.", "NYSE", "E-commerce Platform"),
        ("MELI", "MercadoLibre Inc.", "NASDAQ", "Latin America E-commerce"),
        ("PDD", "PDD Holdings (Temu)", "NASDAQ", "E-commerce"),
        ("BABA", "Alibaba Group", "NYSE", "Cloud & E-commerce"),
        ("TSM", "Taiwan Semiconductor", "NYSE", "Semiconductor Foundry"),
        ("ASML", "ASML Holding NV", "NASDAQ", "Lithography Equipment"),
        ("NVO", "Novo Nordisk A/S", "NYSE", "Pharmaceuticals"),
        ("AZN", "AstraZeneca plc", "NASDAQ", "Pharmaceuticals"),
        ("NVS", "Novartis AG", "NYSE", "Pharmaceuticals"),
        ("TM", "Toyota Motor Corp.", "NYSE", "Automotive"),
        ("SAP", "SAP SE", "NYSE", "Enterprise Software"),
        ("SHEL", "Shell plc", "NYSE", "Integrated Oil & Gas"),
        ("BTI", "British American Tobacco", "NYSE", "Tobacco"),
        ("SNY", "Sanofi", "NASDAQ", "Pharmaceuticals")
    ]

    for sym, name, exch, sec in us_megacaps:
        assets.append(Asset(
            symbol=f"{exch}:{sym}",
            name=name,
            asset_class=AssetClass.US_STOCK,
            exchange=exch,
            sector=sec,
            currency="USD",
            requires_financials=True
        ))

    # Kalan 400 S&P hissesini dinamik olarak ekle (SP500 tamamlayıcı)
    extra_sp500 = [
        ("A", "Agilent Technologies", "NYSE", "Healthcare"), ("AAL", "American Airlines", "NASDAQ", "Industrials"),
        ("AAP", "Advance Auto Parts", "NYSE", "Consumer Discretionary"), ("ABNB", "Airbnb Inc.", "NASDAQ", "Consumer Discretionary"),
        ("ACGL", "Arch Capital Group", "NASDAQ", "Financials"), ("ADM", "Archer-Daniels-Midland", "NYSE", "Consumer Staples"),
        ("AEE", "Ameren Corp.", "NYSE", "Utilities"), ("AEP", "American Electric Power", "NASDAQ", "Utilities"),
        ("AES", "AES Corp.", "NYSE", "Utilities"), ("AFL", "Aflac Inc.", "NYSE", "Financials"),
        ("AIG", "American International Group", "NYSE", "Financials"), ("AIZ", "Assurant Inc.", "NYSE", "Financials"),
        ("AJG", "Arthur J. Gallagher", "NYSE", "Financials"), ("AKAM", "Akamai Technologies", "NASDAQ", "Technology"),
        ("ALB", "Albemarle Corp.", "NYSE", "Materials"), ("ALGN", "Align Technology", "NASDAQ", "Healthcare"),
        ("ALL", "Allstate Corp.", "NYSE", "Financials"), ("ALLE", "Allegion plc", "NYSE", "Industrials"),
        ("ALNY", "Alnylam Pharmaceuticals", "NASDAQ", "Healthcare"), ("AMCR", "Amcor plc", "NYSE", "Materials"),
        ("AME", "AMETEK Inc.", "NYSE", "Industrials"), ("AMP", "Ameriprise Financial", "NYSE", "Financials"),
        ("AMT", "American Tower Corp.", "NYSE", "Real Estate"), ("ANSS", "ANSYS Inc.", "NASDAQ", "Technology"),
        ("AON", "Aon plc", "NYSE", "Financials"), ("AOS", "A. O. Smith Corp.", "NYSE", "Industrials"),
        ("APA", "APA Corp.", "NASDAQ", "Energy"), ("APD", "Air Products and Chemicals", "NYSE", "Materials"),
        ("APH", "Amphenol Corp.", "NYSE", "Technology"), ("APTV", "Aptiv plc", "NYSE", "Consumer Discretionary"),
        ("ARE", "Alexandria Real Estate", "NYSE", "Real Estate"), ("ATO", "Atmos Energy", "NYSE", "Utilities"),
        ("AVB", "AvalonBay Communities", "NYSE", "Real Estate"), ("AVY", "Avery Dennison", "NYSE", "Materials"),
        ("AWK", "American Water Works", "NYSE", "Utilities"), ("AXON", "Axon Enterprise", "NASDAQ", "Industrials"),
        ("AXP", "American Express Co.", "NYSE", "Financials"), ("AZO", "AutoZone Inc.", "NYSE", "Consumer Discretionary"),
        ("BALL", "Ball Corp.", "NYSE", "Materials"), ("BAX", "Baxter International", "NYSE", "Healthcare"),
        ("BBY", "Best Buy Co. Inc.", "NYSE", "Consumer Discretionary"), ("BDX", "Becton Dickinson", "NYSE", "Healthcare"),
        ("BEN", "Franklin Resources", "NYSE", "Financials"), ("BF.B", "Brown-Forman Corp.", "NYSE", "Consumer Staples"),
        ("BG", "Bunge Global SA", "NYSE", "Consumer Staples"), ("BIIB", "Biogen Inc.", "NASDAQ", "Healthcare"),
        ("BIO", "Bio-Rad Laboratories", "NYSE", "Healthcare"), ("BK", "Bank of New York Mellon", "NYSE", "Financials"),
        ("BKR", "Baker Hughes Co.", "NASDAQ", "Energy"), ("BLDR", "Builders FirstSource", "NYSE", "Industrials"),
        ("BXP", "BXP Inc.", "NYSE", "Real Estate"), ("CARR", "Carrier Global", "NYSE", "Industrials"),
        ("CBRE", "CBRE Group Inc.", "NYSE", "Real Estate"), ("CCI", "Crown Castle Inc.", "NYSE", "Real Estate"),
        ("CCL", "Carnival Corp.", "NYSE", "Consumer Discretionary"), ("CE", "Celanese Corp.", "NYSE", "Materials"),
        ("CEG", "Constellation Energy", "NASDAQ", "Utilities"), ("CF", "CF Industries", "NYSE", "Materials"),
        ("CFG", "Citizens Financial", "NYSE", "Financials"), ("CHD", "Church & Dwight", "NYSE", "Consumer Staples"),
        ("CHRW", "C.H. Robinson Worldwide", "NASDAQ", "Industrials"), ("CHTR", "Charter Communications", "NASDAQ", "Communication Services"),
        ("CINF", "Cincinnati Financial", "NASDAQ", "Financials"), ("CL", "Colgate-Palmolive", "NYSE", "Consumer Staples"),
        ("CLX", "Clorox Co.", "NYSE", "Consumer Staples"), ("CMA", "Comerica Inc.", "NYSE", "Financials"),
        ("CMCSA", "Comcast Corp.", "NASDAQ", "Communication Services"), ("CME", "CME Group Inc.", "NASDAQ", "Financials"),
        ("CMG", "Chipotle Mexican Grill", "NYSE", "Consumer Discretionary"), ("CMI", "Cummins Inc.", "NYSE", "Industrials"),
        ("CMS", "CMS Energy Corp.", "NYSE", "Utilities"), ("CNC", "Centene Corp.", "NYSE", "Healthcare"),
        ("CNP", "CenterPoint Energy", "NYSE", "Utilities"), ("COF", "Capital One Financial", "NYSE", "Financials"),
        ("COO", "The Cooper Companies", "NASDAQ", "Healthcare"), ("CPAY", "Corpay Inc.", "NYSE", "Financials"),
        ("CPB", "Campbell Soup Co.", "NYSE", "Consumer Staples"), ("CPRT", "Copart Inc.", "NASDAQ", "Industrials"),
        ("CPT", "Camden Property Trust", "NYSE", "Real Estate"), ("CRL", "Charles River Labs", "NYSE", "Healthcare"),
        ("CSGP", "CoStar Group Inc.", "NASDAQ", "Real Estate"), ("CSX", "CSX Corp.", "NASDAQ", "Industrials"),
        ("CTAS", "Cintas Corp.", "NASDAQ", "Industrials"), ("CTLT", "Catalent Inc.", "NYSE", "Healthcare"),
        ("CTRA", "Coterra Energy", "NYSE", "Energy"), ("CTSH", "Cognizant Technology", "NASDAQ", "Technology"),
        ("CTVA", "Corteva Inc.", "NYSE", "Materials"), ("CVS", "CVS Health Corp.", "NYSE", "Healthcare"),
        ("CZR", "Caesars Entertainment", "NASDAQ", "Consumer Discretionary"), ("D", "Dominion Energy", "NYSE", "Utilities"),
        ("DAL", "Delta Air Lines", "NYSE", "Industrials"), ("DAY", "Dayforce Inc.", "NYSE", "Technology"),
        ("DD", "DuPont de Nemours", "NYSE", "Materials"), ("DFS", "Discover Financial", "NYSE", "Financials"),
        ("DG", "Dollar General Corp.", "NYSE", "Consumer Staples"), ("DGX", "Quest Diagnostics", "NYSE", "Healthcare"),
        ("DHI", "D.R. Horton Inc.", "NYSE", "Consumer Discretionary"), ("DHR", "Danaher Corp.", "NYSE", "Healthcare"),
        ("DLTR", "Dollar Tree Inc.", "NASDAQ", "Consumer Staples"), ("DOC", "Healthpeak Properties", "NYSE", "Real Estate"),
        ("DOV", "Dover Corp.", "NYSE", "Industrials"), ("DOW", "Dow Inc.", "NYSE", "Materials"),
        ("DPZ", "Domino's Pizza Inc.", "NYSE", "Consumer Discretionary"), ("DRI", "Darden Restaurants", "NYSE", "Consumer Discretionary"),
        ("DTE", "DTE Energy Co.", "NYSE", "Utilities"), ("DUK", "Duke Energy Corp.", "NYSE", "Utilities"),
        ("DVA", "DaVita Inc.", "NYSE", "Healthcare"), ("DVN", "Devon Energy Corp.", "NYSE", "Energy"),
        ("DXCM", "DexCom Inc.", "NASDAQ", "Healthcare"), ("EA", "Electronic Arts", "NASDAQ", "Communication Services"),
        ("EBAY", "eBay Inc.", "NASDAQ", "Consumer Discretionary"), ("ECL", "Ecolab Inc.", "NYSE", "Materials"),
        ("ED", "Consolidated Edison", "NYSE", "Utilities"), ("EFX", "Equifax Inc.", "NYSE", "Financials"),
        ("EG", "Everest Group Ltd.", "NYSE", "Financials"), ("EIX", "Edison International", "NYSE", "Utilities"),
        ("EL", "Estee Lauder Companies", "NYSE", "Consumer Staples"), ("EMN", "Eastman Chemical", "NYSE", "Materials"),
        ("EMR", "Emerson Electric Co.", "NYSE", "Industrials"), ("ENPH", "Enphase Energy", "NASDAQ", "Technology"),
        ("EOG", "EOG Resources", "NYSE", "Energy"), ("EPAM", "EPAM Systems", "NYSE", "Technology"),
        ("EQIX", "Equinix Inc.", "NASDAQ", "Real Estate"), ("EQR", "Equity Residential", "NYSE", "Real Estate"),
        ("EQT", "EQT Corp.", "NYSE", "Energy"), ("ERIE", "Erie Indemnity Co.", "NASDAQ", "Financials"),
        ("ES", "Eversource Energy", "NYSE", "Utilities"), ("ESS", "Essex Property Trust", "NYSE", "Real Estate"),
        ("ETN", "Eaton Corp. plc", "NYSE", "Industrials"), ("ETR", "Entergy Corp.", "NYSE", "Utilities"),
        ("EVRG", "Evergy Inc.", "NASDAQ", "Utilities"), ("EW", "Edwards Lifesciences", "NYSE", "Healthcare"),
        ("EXC", "Exelon Corp.", "NASDAQ", "Utilities"), ("EXPD", "Expeditors International", "NASDAQ", "Industrials"),
        ("EXPE", "Expedia Group Inc.", "NASDAQ", "Consumer Discretionary"), ("EXR", "Extra Space Storage", "NYSE", "Real Estate"),
        ("F", "Ford Motor Co.", "NYSE", "Consumer Discretionary"), ("FANG", "Diamondback Energy", "NASDAQ", "Energy"),
        ("FAST", "Fastenal Co.", "NASDAQ", "Industrials"), ("FCX", "Freeport-McMoRan", "NYSE", "Materials"),
        ("FDS", "FactSet Research Systems", "NYSE", "Financials"), ("FDX", "FedEx Corp.", "NYSE", "Industrials"),
        ("FE", "FirstEnergy Corp.", "NYSE", "Utilities"), ("FFIV", "F5 Inc.", "NASDAQ", "Technology"),
        ("FICO", "Fair Isaac Corp.", "NYSE", "Technology"), ("FIS", "Fidelity National Information", "NYSE", "Financials"),
        ("FITB", "Fifth Third Bancorp", "NASDAQ", "Financials"), ("FMC", "FMC Corp.", "NYSE", "Materials"),
        ("FOX", "Fox Corp. (Class B)", "NASDAQ", "Communication Services"), ("FOXA", "Fox Corp. (Class A)", "NASDAQ", "Communication Services"),
        ("FRT", "Federal Realty Investment", "NYSE", "Real Estate"), ("FSLR", "First Solar Inc.", "NASDAQ", "Technology"),
        ("FTNT", "Fortinet Inc.", "NASDAQ", "Technology"), ("FTV", "Fortive Corp.", "NYSE", "Industrials"),
        ("GD", "General Dynamics", "NYSE", "Industrials"), ("GDDY", "GoDaddy Inc.", "NYSE", "Technology"),
        ("GEN", "Gen Digital Inc.", "NASDAQ", "Technology"), ("GFL", "GFL Environmental", "NYSE", "Industrials"),
        ("GGP", "General Growth Properties", "NYSE", "Real Estate"), ("GIB", "CGI Inc.", "NYSE", "Technology"),
        ("GL", "Globe Life Inc.", "NYSE", "Financials"), ("GLW", "Corning Inc.", "NYSE", "Technology"),
        ("GM", "General Motors", "NYSE", "Consumer Discretionary"), ("GNRC", "Generac Holdings", "NYSE", "Industrials"),
        ("GPC", "Genuine Parts Co.", "NYSE", "Consumer Discretionary"), ("GPK", "Graphic Packaging", "NYSE", "Materials"),
        ("GPN", "Global Payments Inc.", "NYSE", "Financials"), ("GRMN", "Garmin Ltd.", "NYSE", "Consumer Discretionary"),
        ("GSK", "GlaxoSmithKline", "NYSE", "Healthcare"), ("GWW", "W.W. Grainger Inc.", "NYSE", "Industrials"),
        ("HAL", "Halliburton Co.", "NYSE", "Energy"), ("HAS", "Hasbro Inc.", "NASDAQ", "Consumer Discretionary"),
        ("HBAN", "Huntington Bancshares", "NASDAQ", "Financials"), ("HCA", "HCA Healthcare Inc.", "NYSE", "Healthcare"),
        ("HES", "Hess Corp.", "NYSE", "Energy"), ("HIG", "Hartford Financial Services", "NYSE", "Financials"),
        ("HII", "Huntington Ingalls Industries", "NYSE", "Industrials"), ("HLT", "Hilton Worldwide", "NYSE", "Consumer Discretionary"),
        ("HOLX", "Hologic Inc.", "NASDAQ", "Healthcare"), ("HPE", "Hewlett Packard Enterprise", "NYSE", "Technology"),
        ("HPQ", "HP Inc.", "NYSE", "Technology"), ("HRL", "Hormel Foods Corp.", "NYSE", "Consumer Staples"),
        ("HSIC", "Henry Schein Inc.", "NASDAQ", "Healthcare"), ("HST", "Host Hotels & Resorts", "NASDAQ", "Real Estate"),
        ("HSY", "The Hershey Co.", "NYSE", "Consumer Staples"), ("HUBB", "Hubbell Inc.", "NYSE", "Industrials"),
        ("HUM", "Humana Inc.", "NYSE", "Healthcare"), ("HWM", "Howmet Aerospace", "NYSE", "Industrials"),
        ("HZNP", "Horizon Therapeutics", "NASDAQ", "Healthcare"), ("IAC", "IAC Inc.", "NASDAQ", "Communication Services"),
        ("IART", "Integra LifeSciences", "NASDAQ", "Healthcare"), ("ICUI", "ICU Medical", "NASDAQ", "Healthcare"),
        ("IDA", "IDACORP Inc.", "NYSE", "Utilities"), ("IDXX", "IDEXX Laboratories", "NASDAQ", "Healthcare"),
        ("IEX", "IDEX Corp.", "NYSE", "Industrials"), ("IFF", "International Flavors & Fragrances", "NYSE", "Materials"),
        ("ILMN", "Illumina Inc.", "NASDAQ", "Healthcare"), ("INCY", "Incyte Corp.", "NASDAQ", "Healthcare"),
        ("INSP", "Inspire Medical Systems", "NYSE", "Healthcare"), ("INTC", "Intel Corp.", "NASDAQ", "Technology"),
        ("INVH", "Invitation Homes", "NYSE", "Real Estate"), ("IP", "International Paper", "NYSE", "Materials"),
        ("IPG", "Interpublic Group", "NYSE", "Communication Services"), ("IQV", "IQVIA Holdings", "NYSE", "Healthcare"),
        ("IR", "Ingersoll Rand", "NYSE", "Industrials"), ("IRM", "Iron Mountain Inc.", "NYSE", "Real Estate"),
        ("IT", "Gartner Inc.", "NYSE", "Technology"), ("ITW", "Illinois Tool Works", "NYSE", "Industrials"),
        ("IVZ", "Invesco Ltd.", "NYSE", "Financials"), ("J", "Jacobs Solutions Inc.", "NYSE", "Industrials"),
        ("JBHT", "J.B. Hunt Transport", "NASDAQ", "Industrials"), ("JCI", "Johnson Controls", "NYSE", "Industrials"),
        ("JKHY", "Jack Henry & Associates", "NASDAQ", "Technology"), ("JLL", "Jones Lang LaSalle", "NYSE", "Real Estate"),
        ("JNPR", "Juniper Networks", "NYSE", "Technology"), ("K", "Kellanova", "NYSE", "Consumer Staples"),
        ("KDP", "Keurig Dr Pepper", "NASDAQ", "Consumer Staples"), ("KEY", "KeyCorp", "NYSE", "Financials"),
        ("KEYS", "Keysight Technologies", "NYSE", "Technology"), ("KHC", "The Kraft Heinz Co.", "NASDAQ", "Consumer Staples"),
        ("KIM", "Kimco Realty", "NYSE", "Real Estate"), ("KKR", "KKR & Co. Inc.", "NYSE", "Financials"),
        ("KMB", "Kimberly-Clark", "NYSE", "Consumer Staples"), ("KMI", "Kinder Morgan", "NYSE", "Energy"),
        ("KMX", "CarMax Inc.", "NYSE", "Consumer Discretionary"), ("KNX", "Knight-Swift Transportation", "NYSE", "Industrials"),
        ("KR", "The Kroger Co.", "NYSE", "Consumer Staples"), ("KVUE", "Kenvue Inc.", "NYSE", "Consumer Staples"),
        ("L", "Loews Corp.", "NYSE", "Financials"), ("LDOS", "Leidos Holdings", "NYSE", "Industrials"),
        ("LEN", "Lennar Corp.", "NYSE", "Consumer Discretionary"), ("LH", "Labcorp", "NYSE", "Healthcare"),
        ("LHX", "L3Harris Technologies", "NYSE", "Industrials"), ("LKQ", "LKQ Corp.", "NASDAQ", "Consumer Discretionary"),
        ("LNT", "Alliant Energy", "NASDAQ", "Utilities"), ("LNW", "Light & Wonder", "NASDAQ", "Consumer Discretionary"),
        ("LOGI", "Logitech International", "NASDAQ", "Technology"), ("LPLA", "LPL Financial Holdings", "NASDAQ", "Financials"),
        ("LULU", "Lululemon Athletica", "NASDAQ", "Consumer Discretionary"), ("LUV", "Southwest Airlines", "NYSE", "Industrials"),
        ("LYB", "LyondellBasell Industries", "NYSE", "Materials"), ("LYV", "Live Nation Entertainment", "NYSE", "Communication Services"),
        ("MAA", "Mid-America Apartment", "NYSE", "Real Estate"), ("MAR", "Marriott International", "NASDAQ", "Consumer Discretionary"),
        ("MAS", "Masco Corp.", "NYSE", "Industrials"), ("MCO", "Moody's Corp.", "NYSE", "Financials"),
        ("MCK", "McKesson Corp.", "NYSE", "Healthcare"), ("MCHP", "Microchip Technology", "NASDAQ", "Technology"),
        ("MHK", "Mohawk Industries", "NYSE", "Consumer Discretionary"), ("MKC", "McCormick & Co.", "NYSE", "Consumer Staples"),
        ("MKTX", "MarketAxess Holdings", "NASDAQ", "Financials"), ("MLM", "Martin Marietta Materials", "NYSE", "Materials"),
        ("MNST", "Monster Beverage", "NASDAQ", "Consumer Staples"), ("MO", "Altria Group Inc.", "NYSE", "Consumer Staples"),
        ("MOH", "Molina Healthcare", "NYSE", "Healthcare"), ("MOS", "The Mosaic Co.", "NYSE", "Materials"),
        ("MPC", "Marathon Petroleum", "NYSE", "Energy"), ("MPW", "Medical Properties Trust", "NYSE", "Real Estate"),
        ("MRNA", "Moderna Inc.", "NASDAQ", "Healthcare"), ("MSCI", "MSCI Inc.", "NYSE", "Financials"),
        ("MSI", "Motorola Solutions", "NYSE", "Technology"), ("MTB", "M&T Bank Corp.", "NYSE", "Financials"),
        ("MTCH", "Match Group Inc.", "NASDAQ", "Communication Services"), ("MTD", "Mettler-Toledo International", "NYSE", "Healthcare"),
        ("NCLH", "Norwegian Cruise Line", "NYSE", "Consumer Discretionary"), ("NDAQ", "Nasdaq Inc.", "NASDAQ", "Financials"),
        ("NDSN", "Nordson Corp.", "NASDAQ", "Industrials"), ("NEE", "NextEra Energy", "NYSE", "Utilities"),
        ("NEM", "Newmont Corp.", "NYSE", "Materials"), ("NI", "NiSource Inc.", "NYSE", "Utilities"),
        ("NKE", "NIKE Inc.", "NYSE", "Consumer Discretionary"), ("NOC", "Northrop Grumman", "NYSE", "Industrials"),
        ("NRG", "NRG Energy", "NYSE", "Utilities"), ("NSC", "Norfolk Southern", "NYSE", "Industrials"),
        ("NTAP", "NetApp Inc.", "NASDAQ", "Technology"), ("NTRS", "Northern Trust", "NASDAQ", "Financials"),
        ("NVR", "NVR Inc.", "NYSE", "Consumer Discretionary"), ("NWL", "Newell Brands", "NASDAQ", "Consumer Discretionary"),
        ("NWS", "News Corp. (Class B)", "NASDAQ", "Communication Services"), ("NWSA", "News Corp. (Class A)", "NASDAQ", "Communication Services"),
        ("NXPI", "NXP Semiconductors", "NASDAQ", "Technology"), ("O", "Realty Income Corp.", "NYSE", "Real Estate"),
        ("ODFL", "Old Dominion Freight Line", "NASDAQ", "Industrials"), ("OGN", "Organon & Co.", "NYSE", "Healthcare"),
        ("OKE", "ONEOK Inc.", "NYSE", "Energy"), ("OMC", "Omnicom Group", "NYSE", "Communication Services"),
        ("ON", "ON Semiconductor", "NASDAQ", "Technology"), ("OTIS", "Otis Worldwide", "NYSE", "Industrials"),
        ("OXY", "Occidental Petroleum", "NYSE", "Energy"), ("PARA", "Paramount Global", "NASDAQ", "Communication Services"),
        ("PAYC", "Paycom Software", "NYSE", "Technology"), ("PAYX", "Paychex Inc.", "NASDAQ", "Industrials"),
        ("PCAR", "PACCAR Inc.", "NASDAQ", "Industrials"), ("PCG", "PG&E Corp.", "NYSE", "Utilities"),
        ("PEAK", "Healthpeak Properties", "NYSE", "Real Estate"), ("PEG", "Public Service Enterprise", "NYSE", "Utilities"),
        ("PENN", "PENN Entertainment", "NASDAQ", "Consumer Discretionary"), ("PFE", "Pfizer Inc.", "NYSE", "Healthcare"),
        ("PFG", "Principal Financial Group", "NASDAQ", "Financials"), ("PG", "Procter & Gamble", "NYSE", "Consumer Staples"),
        ("PGR", "Progressive Corp.", "NYSE", "Financials"), ("PH", "Parker-Hannifin", "NYSE", "Industrials"),
        ("PHM", "PulteGroup Inc.", "NYSE", "Consumer Discretionary"), ("PKG", "Packaging Corp. of America", "NYSE", "Materials"),
        ("PLD", "Prologis Inc.", "NYSE", "Real Estate"), ("PLUG", "Plug Power Inc.", "NASDAQ", "Industrials"),
        ("PNC", "PNC Financial Services", "NYSE", "Financials"), ("PNR", "Pentair plc", "NYSE", "Industrials"),
        ("PNW", "Pinnacle West Capital", "NYSE", "Utilities"), ("PODD", "Insulet Corp.", "NASDAQ", "Healthcare"),
        ("POOL", "Pool Corp.", "NASDAQ", "Consumer Discretionary"), ("PPG", "PPG Industries", "NYSE", "Materials"),
        ("PPL", "PPL Corp.", "NYSE", "Utilities"), ("PRU", "Prudential Financial", "NYSE", "Financials"),
        ("PSA", "Public Storage", "NYSE", "Real Estate"), ("PSX", "Phillips 66", "NYSE", "Energy"),
        ("PTC", "PTC Inc.", "NASDAQ", "Technology"), ("PWR", "Quanta Services", "NYSE", "Industrials"),
        ("PXD", "Pioneer Natural Resources", "NYSE", "Energy"), ("PYPL", "PayPal Holdings", "NASDAQ", "Financials"),
        ("QCOM", "QUALCOMM Inc.", "NASDAQ", "Technology"), ("QRVO", "Qorvo Inc.", "NASDAQ", "Technology"),
        ("RCL", "Royal Caribbean Group", "NYSE", "Consumer Discretionary"), ("REG", "Regency Centers", "NASDAQ", "Real Estate"),
        ("RHI", "Robert Half Inc.", "NYSE", "Industrials"), ("RJF", "Raymond James Financial", "NYSE", "Financials"),
        ("RL", "Ralph Lauren Corp.", "NYSE", "Consumer Discretionary"), ("RMD", "ResMed Inc.", "NYSE", "Healthcare"),
        ("ROK", "Rockwell Automation", "NYSE", "Industrials"), ("ROL", "Rollins Inc.", "NYSE", "Industrials"),
        ("ROP", "Roper Technologies", "NASDAQ", "Technology"), ("ROST", "Ross Stores Inc.", "NASDAQ", "Consumer Discretionary"),
        ("RSG", "Republic Services", "NYSE", "Industrials"), ("RVT", "Royce Value Trust", "NYSE", "Financials"),
        ("RVTY", "Revvity Inc.", "NYSE", "Healthcare"), ("SBAC", "SBA Communications", "NASDAQ", "Real Estate"),
        ("SBNY", "Signature Bank", "NASDAQ", "Financials"), ("SBUX", "Starbucks Corp.", "NASDAQ", "Consumer Discretionary"),
        ("SCCO", "Southern Copper", "NYSE", "Materials"), ("SEDG", "SolarEdge Technologies", "NASDAQ", "Technology"),
        ("SEE", "Sealed Air Corp.", "NYSE", "Materials"), ("SHW", "Sherwin-Williams Co.", "NYSE", "Materials"),
        ("SIVB", "SVB Financial", "NASDAQ", "Financials"), ("SJM", "The J.M. Smucker Co.", "NYSE", "Consumer Staples"),
        ("SLB", "Schlumberger Ltd.", "NYSE", "Energy"), ("SNA", "Snap-on Inc.", "NYSE", "Industrials"),
        ("SO", "Southern Co.", "NYSE", "Utilities"), ("SPG", "Simon Property Group", "NYSE", "Real Estate"),
        ("SRE", "Sempra", "NYSE", "Utilities"), ("STE", "STERIS plc", "NYSE", "Healthcare"),
        ("STLD", "Steel Dynamics", "NASDAQ", "Materials"), ("STT", "State Street Corp.", "NYSE", "Financials"),
        ("STX", "Seagate Technology", "NASDAQ", "Technology"), ("STZ", "Constellation Brands", "NYSE", "Consumer Staples"),
        ("SWK", "Stanley Black & Decker", "NYSE", "Industrials"), ("SWKS", "Skyworks Solutions", "NASDAQ", "Technology"),
        ("SYF", "Synchrony Financial", "NYSE", "Financials"), ("SYK", "Stryker Corp.", "NYSE", "Healthcare"),
        ("SYY", "Sysco Corp.", "NYSE", "Consumer Staples"), ("TAP", "Molson Coors Beverage", "NYSE", "Consumer Staples"),
        ("TDG", "TransDigm Group", "NYSE", "Industrials"), ("TDY", "Teledyne Technologies", "NYSE", "Technology"),
        ("TECH", "Bio-Techne Corp.", "NASDAQ", "Healthcare"), ("TEL", "TE Connectivity", "NYSE", "Technology"),
        ("TER", "Teradyne Inc.", "NASDAQ", "Technology"), ("TFX", "Teleflex Inc.", "NYSE", "Healthcare"),
        ("TGT", "Target Corp.", "NYSE", "Consumer Staples"), ("THC", "Tenet Healthcare", "NYSE", "Healthcare"),
        ("TROW", "T. Rowe Price Group", "NASDAQ", "Financials"), ("TRV", "The Travelers Companies", "NYSE", "Financials"),
        ("TSCO", "Tractor Supply Co.", "NASDAQ", "Consumer Discretionary"), ("TSN", "Tyson Foods Inc.", "NYSE", "Consumer Staples"),
        ("TT", "Trane Technologies", "NYSE", "Industrials"), ("TTWO", "Take-Two Interactive", "NASDAQ", "Communication Services"),
        ("TYL", "Tyler Technologies", "NYSE", "Technology"), ("UDR", "UDR Inc.", "NYSE", "Real Estate"),
        ("UHS", "Universal Health Services", "NYSE", "Healthcare"), ("ULTA", "Ulta Beauty Inc.", "NASDAQ", "Consumer Discretionary"),
        ("URI", "United Rentals Inc.", "NYSE", "Industrials"), ("USB", "U.S. Bancorp", "NYSE", "Financials"),
        ("VFC", "V.F. Corp.", "NYSE", "Consumer Discretionary"), ("VICI", "VICI Properties Inc.", "NYSE", "Real Estate"),
        ("VLO", "Valero Energy Corp.", "NYSE", "Energy"), ("VMC", "Vulcan Materials", "NYSE", "Materials"),
        ("VNO", "Vornado Realty Trust", "NYSE", "Real Estate"), ("VRSK", "Verisk Analytics", "NASDAQ", "Industrials"),
        ("VRSN", "VeriSign Inc.", "NASDAQ", "Technology"), ("VTR", "Ventas Inc.", "NYSE", "Real Estate"),
        ("VTRS", "Viatris Inc.", "NASDAQ", "Healthcare"), ("WAB", "Westinghouse Air Brake", "NYSE", "Industrials"),
        ("WAT", "Waters Corp.", "NYSE", "Healthcare"), ("WBA", "Walgreens Boots Alliance", "NASDAQ", "Healthcare"),
        ("WBD", "Warner Bros. Discovery", "NASDAQ", "Communication Services"), ("WDC", "Western Digital Corp.", "NASDAQ", "Technology"),
        ("WEC", "WEC Energy Group", "NYSE", "Utilities"), ("WELL", "Welltower Inc.", "NYSE", "Real Estate"),
        ("WHR", "Whirlpool Corp.", "NYSE", "Consumer Discretionary"), ("WMB", "Williams Companies", "NYSE", "Energy"),
        ("WRB", "W.R. Berkley Corp.", "NYSE", "Financials"), ("WRK", "WestRock Co.", "NYSE", "Materials"),
        ("WST", "West Pharmaceutical", "NYSE", "Healthcare"), ("WTW", "Willis Towers Watson", "NASDAQ", "Financials"),
        ("WY", "Weyerhaeuser Co.", "NYSE", "Real Estate"), ("WYNN", "Wynn Resorts Ltd.", "NASDAQ", "Consumer Discretionary"),
        ("XEL", "Xcel Energy Inc.", "NASDAQ", "Utilities"), ("XYL", "Xylem Inc.", "NYSE", "Industrials"),
        ("YUM", "Yum! Brands Inc.", "NYSE", "Consumer Discretionary"), ("ZBH", "Zimmer Biomet Holdings", "NYSE", "Healthcare"),
        ("ZBRA", "Zebra Technologies", "NASDAQ", "Technology"), ("ZION", "Zions Bancorporation", "NASDAQ", "Financials"),
        ("ZTS", "Zoetis Inc.", "NYSE", "Healthcare")
    ]

    for sym, name, exch, sec in extra_sp500:
        assets.append(Asset(
            symbol=f"{exch}:{sym}",
            name=name,
            asset_class=AssetClass.US_STOCK,
            exchange=exch,
            sector=sec,
            currency="USD",
            requires_financials=True
        ))

    # (ETFs excluded from fundamental analysis universe)


    # 4. 🪙 Kripto Paralar (20 Kripto)
    crypto_list = [
        ("BTCUSDT", "Bitcoin / Tether"),
        ("ETHUSDT", "Ethereum / Tether"),
        ("SOLUSDT", "Solana / Tether"),
        ("BNBUSDT", "BNB / Tether"),
        ("XRPUSDT", "XRP / Tether"),
        ("ADAUSDT", "Cardano / Tether"),
        ("AVAXUSDT", "Avalanche / Tether"),
        ("DOGEUSDT", "Dogecoin / Tether"),
        ("DOTUSDT", "Polkadot / Tether"),
        ("LINKUSDT", "Chainlink / Tether"),
        ("NEARUSDT", "NEAR Protocol / Tether"),
        ("SUIUSDT", "Sui / Tether"),
        ("APTUSDT", "Aptos / Tether"),
        ("MATICUSDT", "Polygon / Tether"),
        ("LTCUSDT", "Litecoin / Tether"),
        ("BCHUSDT", "Bitcoin Cash / Tether"),
        ("ATOMUSDT", "Cosmos / Tether"),
        ("UNIUSDT", "Uniswap / Tether"),
        ("FETUSDT", "Artificial Superintelligence Alliance"),
        ("RENDERUSDT", "Render / Tether")
    ]

    for sym, name in crypto_list:
        assets.append(Asset(
            symbol=f"BINANCE:{sym}",
            name=name,
            asset_class=AssetClass.CRYPTO,
            exchange="BINANCE",
            sector="Crypto",
            currency="USDT",
            requires_financials=False
        ))

    # 5. 💱 Döviz & Emtia (15 Varlık)
    fx_commodities = [
        ("FX:USDTRY", "Dolar / Türk Lirası", AssetClass.FOREX, "FX", "Forex", "TRY"),
        ("FX:EURTRY", "Euro / Türk Lirası", AssetClass.FOREX, "FX", "Forex", "TRY"),
        ("FX:EURUSD", "Euro / Dolar", AssetClass.FOREX, "FX", "Forex", "USD"),
        ("FX:GBPUSD", "İngiliz Sterlini / Dolar", AssetClass.FOREX, "FX", "Forex", "USD"),
        ("FX:USDJPY", "Dolar / Japon Yeni", AssetClass.FOREX, "FX", "Forex", "JPY"),
        ("FX:USDCHF", "Dolar / İsviçre Frangı", AssetClass.FOREX, "FX", "Forex", "CHF"),
        ("TVC:GOLD", "Ons Altın (XAU/USD)", AssetClass.COMMODITY, "TVC", "Precious Metals", "USD"),
        ("TVC:SILVER", "Ons Gümüş (XAG/USD)", AssetClass.COMMODITY, "TVC", "Precious Metals", "USD"),
        ("TVC:USOIL", "WTI Ham Petrol", AssetClass.COMMODITY, "TVC", "Energy Commodities", "USD"),
        ("TVC:UKOIL", "Brent Petrol", AssetClass.COMMODITY, "TVC", "Energy Commodities", "USD"),
        ("TVC:COPPER", "Bakır Vadeli", AssetClass.COMMODITY, "TVC", "Industrial Metals", "USD"),
        ("TVC:NATGAS", "Doğal Gaz", AssetClass.COMMODITY, "TVC", "Energy Commodities", "USD"),
        ("INDEX:XU100", "BIST 100 Endeksi", AssetClass.INDEX, "INDEX", "Index", "TRY"),
        ("INDEX:SPX", "S&P 500 Endeksi", AssetClass.INDEX, "INDEX", "Index", "USD"),
        ("INDEX:DJI", "Dow Jones Endeksi", AssetClass.INDEX, "INDEX", "Index", "USD"),
        ("INDEX:NDX", "Nasdaq 100 Endeksi", AssetClass.INDEX, "INDEX", "Index", "USD")
    ]

    for sym, name, a_cls, exch, sec, curr in fx_commodities:
        assets.append(Asset(
            symbol=sym,
            name=name,
            asset_class=a_cls,
            exchange=exch,
            sector=sec,
            currency=curr,
            requires_financials=False
        ))

    return assets


def seed_database():
    """Tüm 711 varlığı veritabanına kalıcı olarak yazar"""
    init_db()
    universe = build_711_universe()
    AssetRepository.save_many(universe)
    print(f"✅ Başarıyla {len(universe)} adet varlık veritabanına kaydedildi.")
    return len(universe)


if __name__ == "__main__":
    seed_database()
